name: linting

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:
  pre-job:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          concurrent_skipping: "never"
          skip_after_successful_duplicate: "true"
          do_not_skip: '["pull_request", "workflow_dispatch"]'
  linting:
    name: "pre-commit hooks"
    needs: pre-job
    if: ${{ needs.pre-job.outputs.should_skip != 'true' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      - uses: pre-commit/action@v2.0.0
